# Generated by Django 4.1.3 on 2022-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_instagram_customuser_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
