# Generated by Django 4.1.3 on 2022-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_bio_alter_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
