# Generated by Django 4.1.3 on 2022-12-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='tags',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='uncategorised', max_length=200),
        ),
    ]
