# Generated by Django 4.1.3 on 2022-12-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_newsstory_likes_newsstory_like_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='like_by',
            new_name='liked_by',
        ),
    ]
