# Generated by Django 4.1.3 on 2022-12-16 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0012_alter_newsstory_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
